Merge tag 'android-14.0.0_r0.58' into staging/lineage-21_merge-android-14.0.0_r0.58
Android 14.0.0 release 0.58

# -----BEGIN PGP SIGNATURE-----
#
# iF0EABECAB0WIQRDQNE1cO+UXoOBCWTorT+BmrEOeAUCZeZgDwAKCRDorT+BmrEO
# eDU7AJwI3GFOvYBvlhTIYGLRvHKxMnFZ7gCfYDFlF1tcX7/a3DETT3XSwTwC1cc=
# =UDVv
# -----END PGP SIGNATURE-----
# gpg: Signature made Tue Mar  5 01:58:07 2024 EET
# gpg:                using DSA key 4340D13570EF945E83810964E8AD3F819AB10E78
# gpg: Good signature from "The Android Open Source Project <initial-contribution@android.com>" [marginal]
# gpg: initial-contribution@android.com: Verified 2418 signatures in the past
#      2 years.  Encrypted 4 messages in the past 2 years.
# gpg: WARNING: This key is not certified with sufficiently trusted signatures!
# gpg:          It is not certain that the signature belongs to the owner.
# Primary key fingerprint: 4340 D135 70EF 945E 8381  0964 E8AD 3F81 9AB1 0E78

# By Eric Dumazet (38) and others
# Via Greg Kroah-Hartman (14) and others
* tag 'android-14.0.0_r0.58': (1076 commits)
  Fix After plug in the 3.5mm Audio accessory , system will reboot repeatedly
  bus: mhi: misc: Add check for dev_rp if it is iommu range or not
  Linux 4.19.294
  Revert "ARM: ep93xx: fix missing-prototype warnings"
  Revert "MIPS: Alchemy: fix dbdma2"
  Linux 4.19.293
  dma-buf/sw_sync: Avoid recursive lock during fence signal
  clk: Fix undefined reference to `clk_rate_exclusive_{get,put}'
  scsi: core: raid_class: Remove raid_component_add()
  scsi: snic: Fix double free in snic_tgt_create()
  irqchip/mips-gic: Don't touch vl_map if a local interrupt is not routable
  rtnetlink: Reject negative ifindexes in RTM_NEWLINK
  netfilter: nf_queue: fix socket leak
  sched/rt: pick_next_rt_entity(): check list_entry
  mmc: block: Fix in_flight[issue_type] value error
  x86/fpu: Set X86_FEATURE_OSXSAVE feature after enabling OSXSAVE in CR4
  PCI: acpiphp: Use pci_assign_unassigned_bridge_resources() only for non-root bus
  media: vcodec: Fix potential array out-of-bounds in encoder queue_setup
  lib/clz_ctz.c: Fix __clzdi2() and __ctzdi2() for 32-bit kernels
  batman-adv: Fix batadv_v_ogm_aggr_send memory leak
  ...

Change-Id: I2fb9b62d8faf04d70a603cb14375719fcab844bb